# A single self-contained HTML file a collaborator can open without R:
# the rotatable structure, the static tracks, the ranked table and -- the part
# that matters for honest reporting -- the modelling caveats in plain language.

#' Write a self-contained HTML report for one gene
#'
#' @param res an `xsmut3d_result` from [xsmut3d_pipeline()]
#' @param file output path (.html)
#' @param top number of ranked mutations to tabulate
#' @return the path, invisibly
#' @export
xsmut3d_report <- function(res, file, top = 25L) {
  stopifnot(inherits(res, "xsmut3d_result"))
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)

  fig <- tempfile(fileext = ".png")
  ggplot2::ggsave(fig, res$plot, width = 11, height = 9.5, dpi = 150)
  fig_b64 <- paste0("data:image/png;base64,",
                    jsonlite::base64_enc(readBin(fig, "raw", file.size(fig))))

  view_html <- tempfile(fileext = ".html")
  save_view_html(res$view, view_html)
  view_src <- paste0("data:text/html;base64,",
                     jsonlite::base64_enc(readBin(view_html, "raw", file.size(view_html))))

  tbl <- top_hits(res, top)
  rows <- paste(apply(tbl, 1, function(r)
    paste0("<tr>", paste0("<td>", ifelse(is.na(r), "", as.character(r)), "</td>", collapse = ""), "</tr>")),
    collapse = "\n")
  hdr <- paste0("<th>", names(tbl), "</th>", collapse = "")

  cl <- res$cluster
  cl_txt <- if (is.null(cl) || is.na(cl$p_value)) "Not enough confidently modelled mutated residues to test." else
    sprintf(paste0("Mean recurrence-weighted pairwise distance between mutated residues is %.1f &Aring;, ",
                   "versus %.1f &Aring; expected by chance (z = %.2f, empirical p = %.4g, %d residues, ",
                   "%d mutations; %d residue(s) excluded for pLDDT below the threshold)."),
            cl$observed, cl$null_mean, cl$z, cl$p_value, cl$n_residues, cl$n_mutations,
            cl$excluded_low_confidence)

  transferred <- sum(res$domains$transferred, na.rm = TRUE)
  ann_txt <- if (transferred)
    sprintf("%d of %d annotated features were transferred from the human ortholog (%s) across a %.1f%% identical alignment and are marked with a dashed outline in the figure. Treat transferred point features (active sites, binding sites) as hypotheses about the query species, not observations.",
            transferred, nrow(res$domains), res$target$human_accession,
            suppressWarnings(max(res$domains$transfer_identity, na.rm = TRUE)))
  else "All annotated features come from the entry's own UniProt / InterPro record."

  html <- sprintf('<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>%s &mdash; xsmut3d</title>
<style>
 :root { color-scheme: light; }
 body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, sans-serif;
        max-width: 1100px; margin: 2rem auto; padding: 0 1.25rem; line-height: 1.55; color: #1b1b1f; }
 h1 { font-size: 1.6rem; margin-bottom: 0.2rem; }
 h2 { font-size: 1.15rem; margin-top: 2.2rem; border-bottom: 1px solid #e3e3e8; padding-bottom: .3rem; }
 .meta { color: #5a5a66; font-size: .9rem; }
 .caveat { background: #FFF8E6; border-left: 4px solid #F0B429; padding: .8rem 1rem; border-radius: 4px; }
 table { border-collapse: collapse; width: 100%%; font-size: .82rem; }
 th, td { border-bottom: 1px solid #ececf1; padding: .35rem .5rem; text-align: left; vertical-align: top; }
 th { background: #f6f6f9; position: sticky; top: 0; }
 iframe { width: 100%%; height: 620px; border: 1px solid #e3e3e8; border-radius: 6px; }
 img { width: 100%%; border: 1px solid #e3e3e8; border-radius: 6px; }
 .wrap { max-height: 560px; overflow: auto; border: 1px solid #e3e3e8; border-radius: 6px; }
</style></head><body>
<h1>%s</h1>
<p class="meta">%s &middot; AlphaFold %s (UniProt %s, v%s) &middot; %d calls, %d placed on %d residues</p>

<h2>Structure</h2>
<iframe src="%s" title="interactive structure"></iframe>
<p class="meta">Spheres: mutated residues, sized by recurrence. Green sticks: annotated key functional sites.
In plddt colouring, yellow/orange cartoon = pLDDT &lt; 70, where the coordinates should not be interpreted.</p>

<h2>Model confidence</h2>
<div class="caveat"><p>%s</p><p>%s</p></div>

<h2>Three-dimensional clustering</h2>
<p>%s</p>

<h2>Tracks</h2>
<img src="%s" alt="mutation, domain and confidence tracks">

<h2>Top %d ranked mutations</h2>
<div class="wrap"><table><thead><tr>%s</tr></thead><tbody>
%s
</tbody></table></div>
<p class="meta">Ranking combines recurrence, functional-site proximity in 3D, COSMIC burden at the
aligned human residue, AlphaMissense pathogenicity where available, and is discounted
four-fold for residues below the pLDDT threshold.</p>

<p class="meta">Generated by xsmut3d on %s.</p>
</body></html>',
    res$gene, res$gene,
    if (is.null(res$species)) "Human" else gsub("_", " ", res$species),
    res$model$entry_id, res$model$accession, as.character(res$model$version),
    nrow(res$mutations), sum(!is.na(res$mutations$struct_pos)), nrow(res$residues),
    view_src,
    res$confidence$text, ann_txt,
    cl_txt, fig_b64, top, hdr, rows, format(Sys.Date()))

  writeLines(html, file)
  invisible(normalizePath(file))
}
